### ISSUE TITLE
About dataset binary labeling

### ISSUE THREAD

**Issue by 309020726** [faberno/SurgicalToolLocalization#1]
Hi, first of all, thank you very much for the code.

May I ask what kind of binary labels this training dataset is labeled as? Is it convenient to share it?

I will be very much looking forward to your reply and hope you can help!

**Comment by faberno** [comment]
The training labels are arrays of length n (size depends on dataset) with the index i beeing 1, if this certain tool is present in the image. The labels are built in the read_annotations functions that every dataset class has, by simply reading the name of the image files. So if you have the dataset the labels should be created automatically.

**Comment by 309020726** [comment]
Thank you for your reply
May I ask if the label format is saved as a file(.txt) in the following text format?
Frame	Grasper	Bipolar	Hook	Scissors	Clipper	Irrigator	SpecimenBag
0	1	0	0	0	0	0	0
25	1	0	0	0	0	0	0
50	1	0	0	0	0	0	0
75	1	0	0	0	0	0	0
100	0	0	0	0	0	0	0
. . .
.
.

**Comment by 309020726** [comment]
Thank you for your reply

I carefully checked your code and found that the read-annotations function was not called in "train. py" and "validate. py", but instead the data path provided in the "config_toolloc_m2cai16. json" file was used directly.
May I ask if the correct process for training and testing my own dataset is as follows:
1. First, label each data with the correct bounding box (save it in the form of an ".xml" file)
2. Run the "m2cai16_dataset. py" to convert the tags in the ".xml" file into binary tags and output them
3. Finally, use the output binary labels and raw data images for training and testing

I am very much looking forward to your reply and help, and I would greatly appreciate it.

**Comment by faberno** [comment]
First, the dataset is loaded by providing the name and the datapath in the config{...}.json, as you said. It's then loaded in train.py by create_dataset(config) ->  CustomDatasetDataLoader(config) -> dataset_class(config) -> self.read_annotations()

If you have the bounding boxes and want to test your model on them, that process should be correct, yes. But dont run the {...}_dataset.py but the train.py as the dataset is called from there. 
If you don't have any bounding box labels, but just the names of the present tools, its also possible to just test the detection without the localization.

If you have access to m2cai16 the bounding boxes should be included there.

**Comment by 309020726** [comment]
Okay, thank you very much for your help. Wishing you a happy life and smooth research.

**Comment by 309020726** [comment]
Hello, I'm very sorry to bother you again

I have trained and validated using the m2cai16 dataset (with labels) before. But I want to test my own dataset using the previously trained network, and once again, only run the validate.py file, with an error message indicating that the dataset label is required.
Do I also need labels during the testing process?

PS: The tags I used during my previous training were XML files containing bounding boxes to locate the position of surgical tools, and all trains, val, and tests had corresponding tags. But my own dataset doesn't have labels

Looking forward to your reply very much

**Comment by faberno** [comment]
Without knowing the exact error I can only guess that you need to turn off compute_AP_loc in

[AP = ap_tester.run(compute_AP_loc=True)](https://github.com/faberno/SurgicalToolLocalization/blob/c8f52b63916ffc92fa711cd669109c2b73e9c53f/validate.py#L55C5-L55C44)

**Comment by 309020726** [comment]
The error message is like this：

Reading config file...
Initializing dataset...
{'dataset_name': 'm2cai16', 'dataset_path': 'G:/Dataset/005grasper&irrigator-image', 'set': 'test', 'loader_params': {'batch_size': 5, 'shuffle': False, 'num_workers': 2, 'pin_memory': True}, 'transforms': {'toTensor': True, 'resize': [336, 600], 'normalize': True, 'channelswitcher': False}, 'mean': [0.3241, 0.2207, 0.2154], 'std': [0.2424, 0.2049, 0.2032]}
Traceback (most recent call last):
  File "E:\Code\Surgical-tool\1detection\SurgicalToolLocalization-master\validate.py", line 77, in <module>
    validate(args.configfile)
  File "E:\Code\Surgical-tool\1detection\SurgicalToolLocalization-master\validate.py", line 25, in validate
    val_dataset = create_dataset(configuration['val_dataset_params'])
  File "E:\Code\Surgical-tool\1detection\SurgicalToolLocalization-master\datasets\__init__.py", line 42, in create_dataset
    data_loader = CustomDatasetDataLoader(configuration)
  File "E:\Code\Surgical-tool\1detection\SurgicalToolLocalization-master\datasets\__init__.py", line 54, in __init__
    self.dataset = dataset_class(configuration)
  File "E:\Code\Surgical-tool\1detection\SurgicalToolLocalization-master\datasets\m2cai16_dataset.py", line 61, in __init__
    self.files = self.read_annotations()
  File "E:\Code\Surgical-tool\1detection\SurgicalToolLocalization-master\datasets\m2cai16_dataset.py", line 102, in read_annotations
    tree = ET.parse(self.annotation_path + name + '.xml')
  File "D:\anaconda\envs\xj-env\lib\xml\etree\ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "D:\anaconda\envs\xj-env\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'G:/Dataset/005grasper&irrigator-image\\Annotations/0.xml'

(”G:/Dataset/005grasper&irrigator-image“) It is the path of my own dataset, and I want to use this network for testing to see the results, but it shows no labels.
What I want to ask is why do the testing process also need labels?
